<?xml version="1.0"?>
<package format="2">
  <name>uav_usv_interfaces</name>
  <version>0.1.0</version>
  <description>Common maritime perception, AIS, tracking, risk and COLREGs interfaces.</description>

  <maintainer email="dji@example.com">dji</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>message_generation</build_depend>
  <build_depend>geographic_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>uuid_msgs</build_depend>

  <build_export_depend>geographic_msgs</build_export_depend>
  <build_export_depend>geometry_msgs</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>uuid_msgs</build_export_depend>

  <exec_depend>message_runtime</exec_depend>
  <exec_depend>geographic_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>uuid_msgs</exec_depend>

  <export/>
</package>
