<?xml version="1.0"?>
<package format="3">
  <name>uav_usv_lv_dot_core</name>
  <version>0.1.0</version>
  <description>ROS-independent algorithm interfaces for the native LV-DOT migration.</description>
  <maintainer email="dji@example.com">dji</maintainer>
  <license>Apache-2.0 AND MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <test_depend>rostest</test_depend>

  <export/>
</package>
